### ISSUE TITLE
Deploy using Amplify Console

### ISSUE THREAD

**Issue by viccooper142** [aws-samples/aws-appsync-chat-starter-react#4]
Hi Ed, 
I managed to modify the base code a bit and then get everything running and deployed using `amplify add hosting` and `amplify publish`. Very slick!
I'm curious if you have looked at what steps would need to be added to deploy the code using the new Amplify Console? 
When I tried it an ran into this error:
```
chatql-react-app-reinvent@0.1.0 build-js /codebuild/output/src278605923/src/HearRo_ChatQLv2
react-scripts build
2018-12-20T19:56:19.783Z [INFO]: Creating an optimized production build...
2018-12-20T19:56:24.192Z [INFO]: Failed to compile.
2018-12-20T19:56:24.194Z [INFO]: ./src/App.js
Cannot find file './aws-exports' in './src'.
2018-12-20T19:56:24.210Z [WARNING]: npm
2018-12-20T19:56:24.211Z [WARNING]:  ERR! code ELIFECYCLE
```
I see that aws-exports.js and other files are not copied since they are in .gitignore. Is there an easy way around this using the Amplify command set? Or perhaps a way to use the Amplify Console using Amplify commands?
Thanks,
Vic

**Comment by awsed** [comment]
@viccooper142, in order to use the Amplify Console you can follow the instructions here:

https://docs.aws.amazon.com/amplify/latest/userguide/deploy-backend.html

You'll need to use the beta version of the CLI with the multienv support to create your project and environment. It creates a ```amplify/team-provider-info.json``` file with the details of each environment and it is detected by the Amplify Console accordingly during the build.

You do need to create the resources in your local machine with the Amplify CLI first as per the instructions in the README file in this repository. After everything is setup with multienv in the Amplify Console then you just need to commit changes to your forked repo and it's automatically detected by the Amplify Console.

If you don't want to use multienv beta version of the CLI you would have to commit the aws-exports.js file to your fork. Any changes to your amplify project would have to be done locally then committed separately to your forked repo.

**Comment by awsed** [comment]
And here's a great article explaining the new multienv features: https://read.acloud.guru/multiple-serverless-environments-with-aws-amplify-344759e1be08

**Comment by awsed** [comment]
I updated the instructions with the proper steps, you will need to update the latest .gitignore file in your local machine.

https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular/blob/master/README.md#backend-setup-building-deploying-and-publishing-with-the-amplify-console

**Comment by awsed** [comment]
Sorry, wrong link… this is the correct one: https://github.com/aws-samples/aws-appsync-chat-starter-react/blob/master/README.md#backend-setup-building-deploying-and-publishing-with-the-amplify-console
